name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B compile test-compile

      - name: Run tests
        run: mvn test

    # Дополнительно: можно добавить шаг для запуска сервиса, если он нужен для тестов
    # Например, если app-replan-delivery.jar должен быть запущен
    # - name: Start application
    #   run: java -jar artifacts/app-replan-delivery.jar &
    #   # Подождать, пока сервер запустится
    #   run: sleep 10
    # - name: Run tests with server
    #   run: mvn test